#!/usr/bin/env python3

import colors as c
import time

for verse in range (5):

    for badger in range (11):

        note_length = 0.39
    
        print(c.blue + "Badger!")
        time.sleep(note_length)

    for mushroom in range (2):

        print(c.red + "Mushroom.")
        time.sleep(note_length*2)

















