#!/usr/bin/env python3

import colors as c
import time
print(c.clear)
for verse in range (5):

    for badger in range (12):

        note_length = 0.39
    
        print(c.blue + "Badger!")
        time.sleep(note_length)

    for mushroom in range (2):

        print(c.red + "Mushroom.")
        time.sleep(note_length*2)
    print(c.clear)

print('''
   _____ _   _____    ___    ___    __ __ ______
  / ___// | / /   |  /   |  /   |  / //_// ____/
  \__ \/  |/ / /| | / /| | / /| | / ,<  / __/   
 ___/ / /|  / ___ |/ ___ |/ ___ |/ /| |/ /___   
/____/_/ |_/_/  |_/_/  |_/_/  |_/_/ |_/_____/
''')  
                                                














