#!/usr/bin/env python3
import colors as c

def live():
    ("Yooooooooooooouuuuuuuu WIN!!! OMG YOU GET 1000000000000000000000000000000000000 DOLLAS!!!")
def die():
    ("Theres always another chance... TO LOSE AGAIN AND DIE AGAIN HAHAHAHAHAHAHA!!!")


def ask(question):
    print(c.orange + question)
    answer = input(' ' + c.magenta).lower().strip()
    return answer


print(c.clear)
print(c. red + '''#Oh, hello there chap.''' + c.blue + ''' #Want to cross the Briiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiidge of Death,''' + c.yellow + ''' #you get a cupa tea for crossing it.''')

name = ask(c.orange + "#Your name please?" + c.magenta + ':')

quest = ask(c.orange + "#Why do you wannt to cross?" + c.magenta + ':')

if name in ['lancelot','galahad']:
    color = ask(c.orange + "#Your favorite color please?" + c.magenta + ':')
    if color == 'blue':
        live()
    else:
        die()
elif name in ['mr snuffles','billyjoebobVI','mr snufflesII','mr snufflesIII']:
    yes = ask(c.orange + "#Oh chap yur me favorite person ARRRRRRGGGGHHH!")
    

























































































































































































