#!/usr/bin/env python3

import colors as c

print(c.clear)
print(c.red + "derp")
print(c.blue + "derp")
print(c.yellow + "derp")
print(c.pink +"derp")
print(c.red + "derp")
print(c.blue + "derp")
print(c.yellow + "derp")
print(c.pink + "derp")
print(c.red + "derp")
print(c.blue + "derp")
print(c.yellow + "derp")
print(c.pink + "derp")
