#!/usr/bin/env python3

import random
import time
import colors as c

sides = []

sides.append('''
 -------
|       |
|   o   |
|       |
 _______
 ''')
sides.append('''
 -------
| o     |
|       |
|     o |
 _______
 ''')
sides.append('''
 -------
| o     |
|   o   |
|     o |
 _______
 ''')
sides.append('''
 -------
| o   o |
|       |
| o   o |
 _______
 ''')
sides.append('''
 -------
| o   o |
|   o   |
| o   o |
 _______
 ''')
sides.append('''
 -------
| o   o |
| o   o |
| o   o |
 _______
 ''')
try:
    while True:
        side = random.choice(sides)
        print(c.clear)
        print(c.blue )
        print(side)
        input()

except KeyboardInterrupt:
    print("\b\b\b")
    exit()


