#!/usr/bin/env python3
import colors as c

print(c.clear)
print(c. yellow + "Mmmmmm, multiplication tables.")
print(c. yellow + "What do you want to multiply by?")
number = input(c.yellow + '>' + c.red + ' ')  

for multiplier in range(1,13):
    product = int(number) * multiplier
    form = '{} x {} = {}'
    print(form.format(number,multiplier,product))










