#!/usr/bin/env python3

import colors as c

import time

hours = 0
minutes = 0
seconds = 0
hundredths = 0

def show():
    print(c.clear)
    print(c.magenta + 'Press Ctrl + C to stop!',end=' ', flush=True)
    print(seconds)

#----------------------------------------------------------------------

while True:
    print(c.clear)
    print(c.yellow + 'Hours: ')
    print(hours)
    print(c.yellow + 'Minutes: ')
    print(minutes)
    print(c.yellow + 'Seconds: ')
    print (seconds)
    print(c.yellow + 'Hunderdths: ')
    print(hundredths)
    time.sleep(0.01)
    hundredths += 1
    if hundredths == 100:
        seconds += 1
        hundredths = 0
    if seconds == 60:
        minutes += 1
        seconds + 0
    if minutes == 60:
        hours += 1
        minutes = 0






